#!/bin/bash
set -e

# TODO: Find a way to install this via apt/control
# Commented out because it takes super long to setup on Raspberry Pi 2
#pip3 install flask flask_restful

mkdir -p /var/log/rpi-ac-control

systemctl daemon-reload
systemctl enable ac-control.service
systemctl restart ac-control.service

# Setup ngrok
if [ ! -f /opt/ngrok/ngrok ]; then
    echo "Installing ngrok"
    mkdir -p /opt/ngrok/
    wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip -O /tmp/ngrok-zip
    unzip /tmp/ngrok-zip -d /opt/ngrok/
fi

systemctl enable ngrok.service
systemctl restart ngrok.service

exit 0