#!/bin/bash
set -e

# TODO: Find a way to install this via apt/control
pip3 install flask flask_restful

mkdir -p /var/log/rpi-ac-control

systemctl daemon-reload
systemctl enable ac-control.service
systemctl restart ac-control.service

exit 0